### ISSUE TITLE
Stänga anmälan till event & competition

### ISSUE THREAD

**Issue by carloberg9** [Krisell/gkk-anmalan#1]
Önskas funktionalitet att stänga anmälan och således nya registreringar internt till tävling och funktionärsroller utan att händelsen tas bort. Syftet är att kunna begränsa intern anmälan för att kunna ta in externa tävlande, samt ordna funktionärsschema, startlistor mm. 

Detta vore bra att ha på plats ett par veckor före serie2, dvs önskvärt om det kunde vara möjligt att färdigställa till helgen 4-5 april.

Tack!

**Comment by Krisell** [comment]
Bra idé!

Inga problem att lösa en grundfunktionalitet som uppfyller detta. Ett tillägg är sedan att man kanske vill tillåta administratörer att redigera anmälningar även efter detta datum, ifall något har blivit fel, men jag kan redigera allt redan i nuläget om det skulle uppstå behov.

**Comment by carloberg9** [comment]
Precis! Blir prima 👌.

**Comment by Krisell** [comment]
Nu finns en preliminär lösning, där administratören kan sätta en "Senaste registreringsdag". När denna har passerat kan nya registreringar eller uppdateringar inte längre göras av medlemmarna, men de kan läsa sin ev. anmälan.

Om man explicit vill "stänga" en anmälan är det bara att sätta detta datum till igår eller tidigare.

**Comment by Krisell** [comment]
Det finns nog en del småputs att göra, inte minst grafiskt, så testa gärna vid tillfälle och se om du hittar några knasigheter. Du kan skapa tillfälliga events och ta bort igen, eller justera de som redan finns. Det finns i nuläget inga åtgärder som automatiskt råkar trigga epost-utskick.

**Comment by carloberg9** [comment]
Snyggt! Testade lite och verkar funka grymt bra ju, sjukt snabbt fixat! 👏🏼👏🏼
