### ISSUE TITLE
Design med Tailwind CSS och Tailwind UI

### ISSUE THREAD

**Issue by Krisell** [Krisell/gkk-anmalan#12]
I branchen `tailwind` har jag påbörjat en migrering från Twitter Bootstrap till att använda Tailwind CSS för designen. Tanken är initialt att i princip återskapa samma design som innan, men vissa bitar snyggas samtidigt till, särskilt med hjälp av Tailwind UI.

## Syfte
 * Jag vill bli bättre på Tailwind
 * Jag vill använda Tailwind UI
 * Framtidssäkra designen och göra det enklare att ändra sen

**Comment by Krisell** [comment]
En liten sneak-peek:

Före:
![image](https://user-images.githubusercontent.com/25909128/89019910-5bbfd680-d31e-11ea-9a16-4305049c993b.png)


Efter:
![image](https://user-images.githubusercontent.com/25909128/89019895-56628c00-d31e-11ea-83ed-ebc3919a51db.png)

Före:
![image](https://user-images.githubusercontent.com/25909128/89019997-7db95900-d31e-11ea-8f5b-2da56f7fce15.png)

Efter:
![image](https://user-images.githubusercontent.com/25909128/89020011-84e06700-d31e-11ea-8cea-a51f2496f284.png)

**Comment by carloberg9** [comment]
Stiligt! 👏🏼👏🏼

**Comment by Krisell** [comment]
Klart genom a287f10409886fb3d4a8fdaa4b438a16770b13de
