### ISSUE TITLE
Dokumenthantering

### ISSUE THREAD

**Issue by Krisell** [Krisell/gkk-anmalan#14]
Sedan igår finns en ny undersida för dokument, exempelvis protokoll från styrelsen. Kvar att göra är att låta administratörer hantera dessa med inledningsvis dessa funktioner:

 * Kunna ladda upp ett nytt dokument och ange namn på filen
 * Kunna radera uppladdade dokument
 * Kunna ändra namn på uppladdade dokument (ändra fil behövs inte eftersom man då kan ladda upp ny).
 * Möjligen kunna "dölja" ett dokument som man har laddat upp men för tillfället inte vill visa.

![image](https://user-images.githubusercontent.com/25909128/94681770-423e0980-0324-11eb-8364-281139bc9d65.png)

Överkurs är snyggare visning med förhandsgranskning i miniatyrformat :)

**Comment by carloberg9** [comment]
Snyggt!
