### ISSUE TITLE
Handle lifters born after 2000

### ISSUE THREAD

**Issue by Krisell** [Krisell/gkk-anmalan#15]
The code below needs to be updated to handle lifters born after 2000.
For instance, if Y < 20, use `20` and otherwise `19`. That should cover us for at least 10 years 😄 

https://github.com/Krisell/gkk-anmalan/blob/99b83dc0ba3812788f12be2647f4d5c70bdbe0d7/resources/js/components/AdminCompetition.vue#L259

**Comment by baysideengineer** [comment]
Hey @Krisell , I like to work on this. Can you please assign it to me?

**Comment by Krisell** [comment]
Feel free to make a PR!

**Comment by Krisell** [comment]
And also feel free to extract the JS logic (for exporting the CSV file) to a separate file, something like `js/modules/LiftingCast.js`

**Comment by Krisell** [comment]
Fixed in https://github.com/Krisell/gkk-anmalan/pull/17
