### ISSUE TITLE
Funktionärskontroll

### ISSUE THREAD

**Issue by carloberg9** [Krisell/gkk-anmalan#18]
Hej!

Vi har pratat i styrelsen och ser det som ett stort problem att folk inte anmäler att de kan vara funktionär. Vi har sedan tidigare beslutat att varje medlem bör hjälpa till minst en gång om året för att få delta på våra tävlingar. Därför efterlyser vi stöd på anmälningssidan för att till 2021 kunna med bättre verktyg applicera detta. 

Vi söker således tre funktioner:
- En funktion som kontrollerar om varje medlem har tackat ja till att vara funktionär senaste året.
- Om inte, någon form av påminnelse som visas på anmälningssidan på lämpligt ställe.
- Någon form av funktionalitet att bekräfta vilka som faktiskt hjälpt till på en tävling, ex retroaktivt kunna gå in och bocka i på anmälningslistan. Kan finnas en poäng i att särskilja vilka som erbjudit sig från vilka som närvarade och hjälpte till. (Ex att vi för närvaro med papper och penna på eventet, sen går styrelsemedlem in och bockar i vilka som närvarat). 

Eftersom det är en ganska stor grej vore det bra om vi hade detta på plats till senast årsmötet så vi kan gå igenom detta och eventuella konsekvenser av att inte hjälpa till med föreningen samlad. 

Kom gärna med tankar och funderingar kring det praktiska av detta, eller om du har förslag på hur vi genomför detta på ett så smidigt sätt som möjligt. 

Tack!

Mvh,
Styrelsen genom Calle

**Comment by Krisell** [comment]
Utmärkt idé!

Jag har påbörjat en implementation. Det finns nu live möjligheten att markera medlemmar som "närvarande" eller inte. I listan med medlemmar visas sedan antal gånger medlemmen närvarat totalt och senaste året.

Testa gärna nuvarande funktionen, men notera alltså att detta bara är påbörjat och att vissa delar återstår.

![image](https://user-images.githubusercontent.com/25909128/97803607-b5e87480-1c4a-11eb-91b0-a18e0ceccdbe.png)

![image](https://user-images.githubusercontent.com/25909128/97803610-bed94600-1c4a-11eb-9d31-dff6813153f5.png)

**Comment by carloberg9** [comment]
Super! Var inne och kikade och det ser grymt lovande ut!

Med vänliga hälsningar,
Carl Öberg

**Comment by Krisell** [comment]
Eftersom det inte är tävlingar som vanligt nu avvaktar jag med funktionen för "påminnelse", den skulle drabba nästan alla i så fall. 

Det går nu att efter en tävling markera vilka som hjälpte till, och detta visas sedan i listan över medlemmar. Jag stänger denna issue tillsvidare, men räknar med att vidareutveckling av funktionen krävs när tävlingarna kommit igång som vanligt igen.
