### ISSUE TITLE
Migrera klubbrekord till detta system

### ISSUE THREAD

**Issue by Krisell** [Krisell/gkk-anmalan#2]
Klubbrekorden lagras idag i samma databas som anmälnings-systemet, men enda möjligheten att redigera ett rekord är att göra manuella ändringar i databasen (ex. via phpmyadmin). Ett enkelt gränssnitt för att lägga till nya rekord (för administratörer) skulle kunna integreras i detta system.

Visningen skulle fortfarande kunna ske separat (https://www.gkk-styrkelyft.se/klubbrekord/), åtminstone inledningsvis, och datan hämtas via ett API-anrop (precis som idag).

## Fördelar
 * Smidigare att lägga in nya rekord, reducerar risken för misstag.
 * Flera administratörer (hela styrelsen + IT-admin) kan redigera klubbrekord, och inte bara en person som i dagsläget.
 * Alla gamla rekord kan sparas, och nya läggs till istället för att skriva över. Detta gör att vi i framtiden kommer kunna se rekordens historik och visa ex. top-3.
 * Om vi vill kan vi koppla rekorden till konton i systemet.

## Nackdelar
 * Ökar komplexiteten på detta system. Inget stort problem i praktiken, och ev. kan detta skrivas som en separat modul.

**Comment by carloberg9** [comment]
Grymt bra förslag! Vore fantastiskt om man kunde koppla det till konton 😃

**Comment by Krisell** [comment]
Jag har påbörjat arbetet med detta och skapat en del av den underliggande struktur som behövs och migrerat alla gamla rekord till nya applikationen rent datamässigt (och samtidigt kopplat alla resultat till konton, i de fall personen hade ett konto).

Nästa steg är följande:
 - [x] Rendera listor med rekorden att visa på https://anmalan.gkk-styrkelyft.se/records
 - [x] Låta administratörer administrera rekorden genom att kunna lägga in nya och uppdatera befintliga.

Eftersom detta ska kunna visas även för icke-inloggade användare visas det som ett val även före inloggning:

![image](https://user-images.githubusercontent.com/25909128/112758816-7f900500-8ff0-11eb-963a-80985b3efbe8.png)

**Comment by Krisell** [comment]
Styrelsemedlemmar kan nu lägga in nya klubbrekord (och uppdatera befintliga genom att skapa en ny och ta bort den gamla). Ett rekord ersätter automatiskt ett gammalt förutsatt att det är bättre, så existerande rekord behöver inte tas bort när nya tillkommer. Skulle man råka radera ett rekord finns de kvar men döljs.

**Comment by Krisell** [comment]
Det är inte vackert men det fyller sitt syfte tillsvidare

![image](https://user-images.githubusercontent.com/25909128/118282985-26603000-b4cf-11eb-84e0-1a4a15e26732.png)

**Comment by carloberg9** [comment]
Snyggt! Grymt jobbat!
