### ISSUE TITLE
Dölja passerade events/tävlingar

### ISSUE THREAD

**Issue by Krisell** [Krisell/gkk-anmalan#4]
Tävlingar/events vars datum har passerat (hela tävlingen om det är en fler-dagars) borde döljas per automatik. Kanske ska den fortsatt kunna vara visningsbar för administratörer.

**Comment by carloberg9** [comment]
Toppenförslag! Kanske skulle det vara en bra idé att implementera så administratörer kan visa/dölja tävlingar och funktionärsevent från administratörsvyn? Då skulle det också vara möjligt att proaktivt skapa händelser, ex när vi har ett preliminärt datum, och offentliggöra när det sen är spikat? Så skulle händelserna automatiskt slå över till dolt när datumet passerat 🤔

**Comment by Krisell** [comment]
Nu är det justerat så att passerade tävlingar/events döljs för medlemmarna per automatik. De syns för admin och kan visas för medlemmarna igen genom att justera datumet till framtiden, men det finns kvar i planen att detta ska kunna göras smidigare, så jag lämnar detta issue öppet.

**Comment by Krisell** [comment]
Nu finns också möjligheten för administratörer att alltid visa eller dölja en tävling, eller ställa in på default, vilket innebär att det visas tills det har varit.

![image](https://user-images.githubusercontent.com/25909128/76413899-92f51180-6396-11ea-925b-486b30e460c1.png)
