### ISSUE TITLE
Flera datum för tävling/event

### ISSUE THREAD

**Issue by carloberg9** [Krisell/gkk-anmalan#5]
I nuläget går det enbart att definiera ett datum när man skapar tävlingar, vilket är fallet i de flesta fall. Dock när vi samlar in anmälningar till mästerskap och dylikt sträcker sig de över flera datum. Det vore fint om det gick att definiera flera datum när man skapar tävlingar eller event, ett tidsspann.

**Comment by Krisell** [comment]
Nu finns stöd för flerdagstävlingar, och dessa datum visas sedan på alla ställen där tävlingens datum presenteras.
![image](https://user-images.githubusercontent.com/25909128/76700318-a9f97380-66b6-11ea-9627-17c07d8b672c.png)

![image](https://user-images.githubusercontent.com/25909128/76700406-4de31f00-66b7-11ea-9fbf-167c1dd99032.png)


Samma lösning skulle kunna användas till events, om vi vill, men en svårighet där är att många nog ofta bara kan ena dagen vid ett arrangemang. Detta kan lösas på tre olika sätt:

1. Skapa separata event för varje dag, ex. "FUNKTIONÄRSANMÄLAN Serie 3 LÖRDAG", och att medlemmarna måste svara på varje.

2. Skapa ett event med flera dagar, och låt medlemmarna skriva som kommentar om de bara kan den ena dagen.

3. Skapa ett event med flera dagar, och bygg in stöd för att "bocka i" vilka dagar man kan vid anmälan. Detta kräver en del utveckling och kommer inte kunna vara redo i närtid.

Ett litet problem med (1) och (3) är att det kan vara så att den enskilda medlemmen inte ens själv vet vilken dag han/hon är tillgänglig, eftersom han/hon också är anmäld till tävlingen och kan hjälpa till de dagar han/hon inte tävlar själv. Detta kan lösas med (2) men kräver då manuell kontroll av den som sätter ihop funktionärsschemat.

Jag röstar därför för att köra på (2) och se hur det fungerar.

**Comment by Krisell** [comment]
Löst i 42ccfe5d4d6203f09d3b063e4ec67267ba67da67
Jag gick på alt. 2, dvs exakt samma funktion som för tävling. Man får kanske skriva i event-info-fältet att de som anmäler sig ska skriva om det bara gäller en av dagarna.
